export const REQUEST_DATA = 'loading/REQUEST_DATA'
export const RECEIVED_DATA = 'loading/RECEIVED_DATA'
export const CATCH_ERROR = 'loading/CATCH_ERROR'
export const RESET = 'loading/RESET'
export const LOGIN_VIA_ETH = 'loading/LOGIN_VAI_ETH'
export const GLOBAL_LOGIN_CHECKING = 'loading/GLOBAL_LOGIN_CHECKING'
